import type { ScheduleEvent } from "@/types";

// Local schedule data for the festival. This is the single source of
// truth for /schedule and /today — no database yet, just configuration.
// Update this list to change the published schedule.
export const scheduleEvents: ScheduleEvent[] = [
  // Day 1 — Sep 14: Ganesh Sthapana
  {
    id: "d1-sthapana",
    date: "2026-09-14",
    title: "Ganesh Murti Sthapana",
    description: "Installation of the Ganesh idol at the community pandal.",
    startTime: "06:00",
    endTime: "07:00",
    venue: "Community Hall",
    category: "pooja",
    highlighted: true,
  },
  {
    id: "d1-pratishtha",
    date: "2026-09-14",
    title: "Prana Pratishtha & Aarti",
    description: "Consecration rituals followed by the first aarti.",
    startTime: "08:00",
    endTime: "09:00",
    venue: "Community Hall",
    category: "pooja",
    highlighted: false,
  },
  {
    id: "d1-sandhya-aarti",
    date: "2026-09-14",
    title: "Sandhya Aarti",
    description: "Evening aarti open to all residents.",
    startTime: "18:00",
    endTime: "19:00",
    venue: "Community Hall",
    category: "pooja",
    highlighted: false,
  },
  {
    id: "d1-welcome",
    date: "2026-09-14",
    title: "Welcome Cultural Program",
    description: "An evening of music and dance to welcome Bappa.",
    startTime: "19:30",
    endTime: "21:00",
    venue: "Open Lawn",
    category: "cultural",
    highlighted: false,
  },

  // Day 2 — Sep 15
  {
    id: "d2-morning-aarti",
    date: "2026-09-15",
    title: "Morning Aarti",
    description: "Daily morning aarti.",
    startTime: "07:00",
    endTime: "07:45",
    venue: "Community Hall",
    category: "pooja",
    highlighted: false,
  },
  {
    id: "d2-modak",
    date: "2026-09-15",
    title: "Modak Prasadam Distribution",
    description: "Freshly made modaks distributed as prasadam.",
    startTime: "17:00",
    endTime: "18:00",
    venue: "Prasadam Counter",
    category: "food",
    highlighted: false,
  },
  {
    id: "d2-bhajan",
    date: "2026-09-15",
    title: "Bhajan Sandhya",
    description: "An evening of devotional bhajans.",
    startTime: "19:00",
    endTime: "20:30",
    venue: "Community Hall",
    category: "cultural",
    highlighted: false,
  },

  // Day 3 — Sep 16
  {
    id: "d3-morning-aarti",
    date: "2026-09-16",
    title: "Morning Aarti",
    description: "Daily morning aarti.",
    startTime: "07:00",
    endTime: "07:45",
    venue: "Community Hall",
    category: "pooja",
    highlighted: false,
  },
  {
    id: "d3-fancy-dress",
    date: "2026-09-16",
    title: "Kids Fancy Dress Competition",
    description: "Children dress up as their favourite deities and heroes.",
    startTime: "16:00",
    endTime: "18:00",
    venue: "Open Lawn",
    category: "kids",
    highlighted: true,
  },
  {
    id: "d3-sandhya-aarti",
    date: "2026-09-16",
    title: "Sandhya Aarti",
    description: "Evening aarti open to all residents.",
    startTime: "19:00",
    endTime: "20:00",
    venue: "Community Hall",
    category: "pooja",
    highlighted: false,
  },

  // Day 4 — Sep 17
  {
    id: "d4-morning-aarti",
    date: "2026-09-17",
    title: "Morning Aarti",
    description: "Daily morning aarti.",
    startTime: "07:00",
    endTime: "07:45",
    venue: "Community Hall",
    category: "pooja",
    highlighted: false,
  },
  {
    id: "d4-dance",
    date: "2026-09-17",
    title: "Classical Dance Performance",
    description: "Performances by residents and invited artists.",
    startTime: "18:00",
    endTime: "19:30",
    venue: "Open Lawn",
    category: "cultural",
    highlighted: false,
  },
  {
    id: "d4-dinner",
    date: "2026-09-17",
    title: "Community Dinner",
    description: "Shared festive dinner for all residents.",
    startTime: "20:00",
    endTime: "21:30",
    venue: "Open Lawn",
    category: "food",
    highlighted: false,
  },

  // Day 5 — Sep 18
  {
    id: "d5-morning-aarti",
    date: "2026-09-18",
    title: "Morning Aarti",
    description: "Daily morning aarti.",
    startTime: "07:00",
    endTime: "07:45",
    venue: "Community Hall",
    category: "pooja",
    highlighted: false,
  },
  {
    id: "d5-volunteers",
    date: "2026-09-18",
    title: "Volunteers Coordination Meeting",
    description: "Planning meeting for festival volunteers and committee members.",
    startTime: "10:00",
    endTime: "11:00",
    venue: "Committee Office",
    category: "other",
    highlighted: false,
  },
  {
    id: "d5-sandhya-aarti",
    date: "2026-09-18",
    title: "Sandhya Aarti",
    description: "Evening aarti open to all residents.",
    startTime: "19:00",
    endTime: "20:00",
    venue: "Community Hall",
    category: "pooja",
    highlighted: false,
  },

  // Day 6 — Sep 19
  {
    id: "d6-morning-aarti",
    date: "2026-09-19",
    title: "Morning Aarti",
    description: "Daily morning aarti.",
    startTime: "07:00",
    endTime: "07:45",
    venue: "Community Hall",
    category: "pooja",
    highlighted: false,
  },
  {
    id: "d6-quiz",
    date: "2026-09-19",
    title: "Ganesh Quiz Competition",
    description: "A fun quiz on Ganesh legends for kids, with prizes.",
    startTime: "18:00",
    endTime: "19:00",
    venue: "Community Hall",
    category: "kids",
    highlighted: false,
  },
  {
    id: "d6-orchestra",
    date: "2026-09-19",
    title: "Live Orchestra Night",
    description: "A live band performing devotional and popular hits.",
    startTime: "19:30",
    endTime: "21:30",
    venue: "Open Lawn",
    category: "cultural",
    highlighted: true,
  },

  // Day 7 — Sep 20
  {
    id: "d7-morning-aarti",
    date: "2026-09-20",
    title: "Morning Aarti",
    description: "Daily morning aarti.",
    startTime: "07:00",
    endTime: "07:45",
    venue: "Community Hall",
    category: "pooja",
    highlighted: false,
  },
  {
    id: "d7-mahaprasadam",
    date: "2026-09-20",
    title: "Community Feast (Maha Prasadam)",
    description: "A large community meal served to all residents and guests.",
    startTime: "17:00",
    endTime: "19:00",
    venue: "Open Lawn",
    category: "food",
    highlighted: true,
  },
  {
    id: "d7-sandhya-aarti",
    date: "2026-09-20",
    title: "Sandhya Aarti",
    description: "Evening aarti open to all residents.",
    startTime: "19:30",
    endTime: "20:30",
    venue: "Community Hall",
    category: "pooja",
    highlighted: false,
  },

  // Day 8 — Sep 21
  {
    id: "d8-morning-aarti",
    date: "2026-09-21",
    title: "Morning Aarti",
    description: "Daily morning aarti.",
    startTime: "07:00",
    endTime: "07:45",
    venue: "Community Hall",
    category: "pooja",
    highlighted: false,
  },
  {
    id: "d8-painting",
    date: "2026-09-21",
    title: "Painting & Drawing Competition",
    description: "An art competition for children of all age groups.",
    startTime: "16:00",
    endTime: "18:00",
    venue: "Community Hall",
    category: "kids",
    highlighted: false,
  },
  {
    id: "d8-singing",
    date: "2026-09-21",
    title: "Devotional Singing Competition",
    description: "Residents compete performing devotional songs.",
    startTime: "19:00",
    endTime: "21:00",
    venue: "Open Lawn",
    category: "cultural",
    highlighted: false,
  },

  // Day 9 — Sep 22
  {
    id: "d9-morning-aarti",
    date: "2026-09-22",
    title: "Morning Aarti",
    description: "Daily morning aarti.",
    startTime: "07:00",
    endTime: "07:45",
    venue: "Community Hall",
    category: "pooja",
    highlighted: false,
  },
  {
    id: "d9-mahaaarti",
    date: "2026-09-22",
    title: "Maha Aarti & Pushpanjali",
    description: "A grand aarti with flower offerings, ahead of visarjan day.",
    startTime: "18:00",
    endTime: "19:30",
    venue: "Community Hall",
    category: "pooja",
    highlighted: true,
  },
  {
    id: "d9-prizenight",
    date: "2026-09-22",
    title: "Cultural Night & Prize Distribution",
    description: "Closing cultural performances and prizes for the week's competitions.",
    startTime: "19:30",
    endTime: "21:30",
    venue: "Open Lawn",
    category: "celebration",
    highlighted: false,
  },

  // Day 10 — Sep 23: Visarjan
  {
    id: "d10-uttarpuja",
    date: "2026-09-23",
    title: "Final Aarti & Uttarpuja",
    description: "The final rituals before the idol's farewell.",
    startTime: "06:00",
    endTime: "08:00",
    venue: "Community Hall",
    category: "pooja",
    highlighted: true,
  },
  {
    id: "d10-visarjan",
    date: "2026-09-23",
    title: "Ganpati Visarjan Procession",
    description: "A festive procession accompanying the idol for immersion.",
    startTime: "09:00",
    endTime: "13:00",
    venue: "Community Hall to Lake Point",
    category: "celebration",
    highlighted: true,
  },
  {
    id: "d10-farewell-lunch",
    date: "2026-09-23",
    title: "Farewell Prasadam Lunch",
    description: "A closing shared meal to conclude the festival.",
    startTime: "13:00",
    endTime: "14:00",
    venue: "Open Lawn",
    category: "food",
    highlighted: false,
  },
];
